apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfopartnerinfo
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
    paths:
      - kvPath: oracle/data/prod/creds/emottak-srvsyfopartnerinfo
        mountPath: /secrets/oracle/creds
      - kvPath: oracle/data/prod/config/emottak
        mountPath: /secrets/oracle/config
  webproxy: true
  ingresses:
    - "https://syfopartnerinfo.nais.adeo.no"
  env:
    - name: CLIENT_ID
      value: 55732aaa-9976-4a7b-8342-2e502a3cdce4
    - name: AADACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navno.onmicrosoft.com/oauth2/token
    - name: AADDISCOVERY_URL
      value: https://login.microsoftonline.com/navno.onmicrosoft.com/.well-known/openid-configuration
    - name: JWT_ISSUER
      value: https://sts.windows.net/62366534-1ec3-4962-8869-9b5535279d0b/
    - name: DATABASE_PREFIX
      value: nmp5
    - name: ALLOWED_APP_IDS
      value: 9d4d6e11-1717-44f7-b76c-1a671847bb32,6af19f7a-8e7c-48f0-9518-d827e483774a
