apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfopartnerinfo
  namespace: default
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/dev/creds/emottak_q1-nmt3
        mountPath: /secrets/oracle/creds
      - kvPath: /oracle/data/dev/config/emottak_q1
        mountPath: /secrets/oracle/config
  webproxy: true
  ingresses:
    - "https://syfopartnerinfo.dev.intern.nav.no"
    - "https://syfopartnerinfo.nais.preprod.local"
  env:
    - name: CLIENT_ID
      value: 077b7904-dec5-4d2e-bf69-bb17f56658c2
    - name: AADACCESSTOKEN_URL
      value: https://login.microsoftonline.com/navq.onmicrosoft.com/oauth2/token
    - name: AADDISCOVERY_URL
      value: https://login.microsoftonline.com/navq.onmicrosoft.com/.well-known/openid-configuration
    - name: JWT_ISSUER
      value: https://sts.windows.net/966ac572-f5b7-4bbe-aa88-c76419c0f851/
    - name: DATABASE_PREFIX
      value: nmt3
    - name: ALLOWED_APP_IDS
      value: a99ce657-bce8-4f11-8dd6-5624038f4820,f5510c3d-2510-444d-91a2-5790c1ec39a4
