apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfopartnerinfo
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  accessPolicy:
    inbound:
      rules:
        - application: fastlegerest
          namespace: teamsykefravr
          cluster: dev-fss
        - application: fastlegerest
          namespace: teamsykefravr
          cluster: dev-gcp
        - application: isdialogmelding
          namespace: teamsykefravr
          cluster: dev-gcp
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/dev/creds/emottak_q1-nmt3
        mountPath: /secrets/oracle/creds
      - kvPath: /oracle/data/dev/config/emottak_q1
        mountPath: /secrets/oracle/config
  webproxy: true
  ingresses:
    - "https://syfopartnerinfo.dev.intern.nav.no"
    - "https://syfopartnerinfo.nais.preprod.local"
    - "https://syfopartnerinfo.dev-fss-pub.nais.io"
  env:
    - name: DATABASE_PREFIX
      value: nmt3
