apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfopartnerinfo
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  accessPolicy:
    inbound:
      rules:
        - application: isdialogmelding
          namespace: teamsykefravr
          cluster: prod-gcp
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
  vault:
    enabled: true
    paths:
      - kvPath: oracle/data/prod/creds/emottak-nmp5
        mountPath: /secrets/oracle/creds
      - kvPath: oracle/data/prod/config/emottak
        mountPath: /secrets/oracle/config
  webproxy: true
  ingresses:
    - "https://syfopartnerinfo.intern.nav.no"
    - "https://syfopartnerinfo.nais.adeo.no"
    - "https://syfopartnerinfo.prod-fss-pub.nais.io"
  env:
    - name: DATABASE_PREFIX
      value: nmp5
