name: Deploy to dev-fss

on:
  workflow_dispatch:
    inputs:
      gitCommit:
        description: "Git ref to deploy (the complete hash):"
        required: true
        default: ""

jobs:
  deploy-dev:
    name: Deploy to NAIS Dev-fss
    uses: navikt/isworkflows/.github/workflows/manual-deploy-dev.yml@master
    with:
      git-commit: ${{ github.event.inputs.gitCommit }}
      dev-cluster: dev-fss
    secrets: inherit
