name: main

on: push

jobs:
  build-and-deploy:
    permissions:
      contents: read
      id-token: write
    uses: navikt/isworkflows/.github/workflows/kotlin-build-deploy.yml@master
    with:
      dev-cluster: dev-fss
      prod-cluster: prod-fss
      distroless: false
    secrets: inherit
